// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBgRky9F0MEtY2Ku5RrgLm7CACDOqIVxXc',
    appId: '1:632025936419:web:3693599b6b4d2db6923796',
    messagingSenderId: '632025936419',
    projectId: 'kidscaredemo-e18df',
    authDomain: 'kidscaredemo-e18df.firebaseapp.com',
    databaseURL: 'https://kidscaredemo-e18df-default-rtdb.firebaseio.com',
    storageBucket: 'kidscaredemo-e18df.appspot.com',
    measurementId: 'G-R5HKBNPX1M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCN2mZO5YYtuPNAXCWBU_dRwMdJPjkEcQA',
    appId: '1:632025936419:android:9b81c97783640736923796',
    messagingSenderId: '632025936419',
    projectId: 'kidscaredemo-e18df',
    databaseURL: 'https://kidscaredemo-e18df-default-rtdb.firebaseio.com',
    storageBucket: 'kidscaredemo-e18df.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_6-OgBZwW2m2oPNWUpEZh_Ny_sEa1DW8',
    appId: '1:632025936419:ios:0746841991148c2f923796',
    messagingSenderId: '632025936419',
    projectId: 'kidscaredemo-e18df',
    databaseURL: 'https://kidscaredemo-e18df-default-rtdb.firebaseio.com',
    storageBucket: 'kidscaredemo-e18df.appspot.com',
    iosBundleId: 'com.example.kidsCareDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_6-OgBZwW2m2oPNWUpEZh_Ny_sEa1DW8',
    appId: '1:632025936419:ios:792f47416604687b923796',
    messagingSenderId: '632025936419',
    projectId: 'kidscaredemo-e18df',
    databaseURL: 'https://kidscaredemo-e18df-default-rtdb.firebaseio.com',
    storageBucket: 'kidscaredemo-e18df.appspot.com',
    iosBundleId: 'com.example.kidsCareDemo.RunnerTests',
  );
}
